modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="valentines_day"
version="1.0.0"
displayName="Valentine's day"
credits="Gabryel (Everyting else) and MCcreator (for Modding Application)"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Gabryel"
description='''
Mod for Valentine's day
'''

[[dependencies.valentines_day]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




